import {
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    GOOGLE_API_KEY,
    MAX_EMAIL_ACCOUNTS as MAX_EMAIL_ACCOUNTS_RAW,
  } from '@env';
  
  export const CLIENT_ID = GOOGLE_CLIENT_ID;
  export const CLIENT_SECRET = GOOGLE_CLIENT_SECRET;
  export const API_KEY = GOOGLE_API_KEY;
  export const MAX_EMAIL_ACCOUNTS = parseInt(MAX_EMAIL_ACCOUNTS_RAW) || 3;
  
  
  
